<a href="https://colab.research.google.com/github/Suraj945gh/Antariksh/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

In [26]:
# Making a list into an array , the same can be done with tuples
myarr = np.array([2,3444,5,67] , np.int16)
# Here int16 is a dtype meaning 16 bit integer datatype i.e.
# elements in the array take only 2 bytes of memory
# Hence adding dtype provides memory management

print(myarr)
myarr[3]

[   2 3444    5   67]


67

In [27]:
# Program showing dtype usage
default_array = np.array([1,2,3,4,5])
print("Default Array is : ",default_array)
print("dtype : ",default_array.dtype)
# Here since , no dtype is given ,it'll take the highest one

float_array = np.array([1,2,3,4,5] , np.float16)
print("Float Array is : ",float_array)
print("dtype = ",float_array.dtype)
# Here since we mentioned the dtype , we've managed memory

# Shortcut for dtype is :
newarr = np.array([4,5,33,6,7] , dtype='f4')
print(newarr)
print(newarr.dtype)    # f4 means float 32 as 4 bytes = 32 bits

# Changing the dtype :
newarrr = newarr.astype('i8')
print("After changing the dtype : ",newarrr.dtype)

Default Array is :  [1 2 3 4 5]
dtype :  int64
Float Array is :  [1. 2. 3. 4. 5.]
dtype =  float16
[ 4.  5. 33.  6.  7.]
float32
After changing the dtype :  int64


In [28]:
# Making a nested array
newArr = np.array([[2,34,45,1],[11,34,77,0]])
print(newArr)
print('\n')
print(newArr.shape)  # Tells that there are 2 rows and 4 columns here
print(newArr.dtype)  # Gives the dtype
print(newArr[1,2])
print(newArr[0])
newArr[1,1] = 111  # This changes 2nd element in 2nd row to 111
print('\n')
print(newArr)

strarr = np.array(['hi','hello','kaiseho','bonjour'])
print(strarr.dtype)
# U7 means Unicode (string) and 7 is the max. chars in any one of the elements
print(strarr.size)

[[ 2 34 45  1]
 [11 34 77  0]]


(2, 4)
int64
77
[ 2 34 45  1]


[[  2  34  45   1]
 [ 11 111  77   0]]
<U7
4


In [29]:
# Intrinsic numpy array creation objects i.e. already known functions
zero = np.zeros((2,3))

# zeros() function is used to return a new array of a given shape and type filled with zeros.

In [30]:
zero  # basically gives an array of 2 rows of 3 elements each

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
print(zero.shape)
print(zero.size)
print(zero.dtype)
print(np.zeros((2,4,3,3)))
# It means ki 3*3 ke 4 elements banao and iss configuration ko 2 baar repeat karo

(2, 3)
6
float64
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


In [32]:
# By default the dtype is float in zeros() function
# But you can also change its dtype :
zero2 = np.zeros((3,4),dtype=int)
zero2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
# arange method returns nos. from 0 to n-1

range1 = np.arange(13)      # arange(stop)
print(range1)
range2 = np.arange(3,23)    # arange(start, stop)
print(range2)
range3 = np.arange(5,25,3,dtype=float)  # arange(start, stop, step)
# mentioning dtype is optional
print(range3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
[ 5.  8. 11. 14. 17. 20. 23.]


In [34]:
# linspace returns equally spaced nos. and takes 3 parameters
equal_space = np.linspace(1,6,10)
# Here , basically we're saying gimme 10 equally spaced nos. from 1 to 6
print(equal_space)
print('\n')

space1 = np.linspace(2.,3.)   # If you don't mention num parameter , then by default 50 nos. will be given
print(space1)
print('\n')

space2 = np.linspace(2.0,3.0,num=5) # num parameter means how many nos. do you want from the interval with equal space
print(space2)
print('\n')

space3 = np.linspace (5,13,num=6,endpoint = False , retstep = True)
print(space3)
# Here endpoint means do not include the last sample i.e. 13 here (By default , it is True)
# retstep means return me the step size of the evenly spaced nos.

[1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]


[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]


[2.   2.25 2.5  2.75 3.  ]


(array([ 5.        ,  6.33333333,  7.66666667,  9.        , 10.33333333,
       11.66666667]), 1.3333333333333333)


In [35]:
# empty function gives an array of random values , which you can assign later
randomarr = np.empty((2,4))  # array of 2 rows and 4 columns
print(randomarr)
print('\n')
# You can also define dtype for it , i.e.
randomarr2 = np.empty((2,3),dtype = int)
print(randomarr2)
print('\n')

# empty_like() takes an previously defined array and copies its size into an empty array
emplike = np.empty_like(space2) # Now emplike is same as space2
print(emplike)

[[4.67967842e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


[[4617315517961601024 4618816717837391189 4620317917713181354]
 [4621256167635550208 4622006767573445290 4622757367511340373]]


[2.   2.25 2.5  2.75 3.  ]


In [36]:
# identity() function
# The identity array is a square array with ones on the main diagonal
iden = np.identity(55)
print(iden)   # Gives an identity matrix of 55 X 55 elements
print(iden.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(55, 55)


In [37]:
arr = np.arange(45)
print(arr)
print('\n')
# It basically reshapes a provided array but remem that elements in each row should be same , otherwise it'll throw error
arr = arr.reshape(5,9)   # This func. generates a 2d array for us
print(arr)
print('\n')

# Now to again have our 1d array , use ravel() function
arr = arr.ravel()
print(arr)
print(arr.shape)  # Gives us a 1d array ka length

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]


[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
(45,)


In [38]:
x = [[1,2,3] , [4,5,6] , [7,1,0]]
Arr = np.array(x)
print(Arr)
print( "Sum of all column elements :", Arr.sum(axis=0))
print("Sum of all row elements : ", Arr.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 1 0]]
Sum of all column elements : [12  8  9]
Sum of all row elements :  [ 6 15  8]


In [39]:
# Attributes and functions :
# Here onwards a thing without () is an attribute and with it is a function
# To transpose an array (Arr):
Arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [40]:
Arr.flat  # A 1-D iterator over the array
for i in Arr.flat:
  print(i)

Arr2 = np.arange(20).reshape(5,4)  # Made a 2d array
print(Arr2)
print("A section from array : ",Arr2.flat[4:11])  # Used iterator to give the values
Arr2.flat = 9      # Setting all the values to 9
print(Arr2)
Arr2.flat[1:8] = 1      # Changing some values in the array
Arr2.flat[13:18] = 77
print(Arr2)

1
2
3
4
5
6
7
1
0
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
A section from array :  [ 4  5  6  7  8  9 10]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
[[ 9  1  1  1]
 [ 1  1  1  1]
 [ 9  9  9  9]
 [ 9 77 77 77]
 [77 77  9  9]]


In [41]:
print(Arr2.ndim)  # Gives the dimension of the array
print("Dimensions : ")
ele0d = np.array(33)
print(ele0d.ndim)
ele1d = np.array([2,4,3,4,55])
print(ele1d.ndim)
ele2d = np.array([[1,2,3] , [3,5,4]])
print(ele2d.ndim)
ele3d = np.array([ [[1,1,11,1],[2,2,78,2]] , [[3,3,56,3],[4,5,55,33]] ])
print(ele3d.ndim)
# Array indexing
print(ele3d[0,1,:3])  # Here :3 means to start from beginning and go all the way to 1 less than the no. mentioned
                      # Here the default step size is 1
print(ele3d[1,1,::2]) # Here ::2 means ki starting se shuru karo but step size 2 rakho

print('\n')
print(Arr2.size)  # Gives the no. of elements in the array
print(Arr2.dtype)
print(Arr2.nbytes)  # Gives info abt total bytes consumed by your array
# Since int64 is the dtype so it means 64 bits i.e. 8 bytes
# Hence every element uses 8 bytes of data , so here 8*20 = 160 bytes

2
Dimensions : 
0
1
2
3
[ 2  2 78]
[ 4 55]


20
int64
160


In [42]:
Arr3 = np.array([2,33,5,343,1])
print("Min element is at index : ", Arr3.argmin())
print("Max element is at index : ", Arr3.argmax())
print(Arr3.argsort())
# So argsort() gives back the array of indices in sorted fashion and not the actual sorted elements
print('\n')
# Experimenting in 2d array :
print(Arr)
print(Arr.argmin()) # It basically converts the 2d array to 1d and then gives us the index of min and max element
print(Arr.argmax())
# Accessing max and min using axis
print(Arr.argmax(axis=0))
print(Arr.argmax(axis=1))
print("Sorted 2d array :\n",Arr.argsort(axis =0))   # Returns array of sorted indices
print(Arr.ravel())
print(Arr.reshape(9,1))

Min element is at index :  4
Max element is at index :  3
[4 0 2 1 3]


[[1 2 3]
 [4 5 6]
 [7 1 0]]
8
6
[2 1 1]
[2 2 0]
Sorted 2d array :
 [[0 2 2]
 [1 0 0]
 [2 1 1]]
[1 2 3 4 5 6 7 1 0]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [1]
 [0]]


In [43]:
# Mathematical operations in numpy i.e. matrix operations
ar1 = np.array([[1,2,3] , [0,4,1] , [7,5,0]])
ar2 = np.array([[8,3,9] , [1,3,8] , [2,3,1]])
add = ar1 + ar2
print("Addition : \n" ,add)
sub = ar1 - ar2
print("Subtraction : \n" ,sub)
mul = ar1 * ar2
print("Multiplication : \n", mul)
div = ar1/ar2
print("Division : \n",div)
rem = ar1%ar2
print("Remainder : \n",rem)

Addition : 
 [[ 9  5 12]
 [ 1  7  9]
 [ 9  8  1]]
Subtraction : 
 [[-7 -1 -6]
 [-1  1 -7]
 [ 5  2 -1]]
Multiplication : 
 [[ 8  6 27]
 [ 0 12  8]
 [14 15  0]]
Division : 
 [[0.125      0.66666667 0.33333333]
 [0.         1.33333333 0.125     ]
 [3.5        1.66666667 0.        ]]
Remainder : 
 [[1 2 3]
 [0 1 1]
 [1 2 0]]


In [44]:
# Getting squareroot of the array
sqrt = np.sqrt(ar2)
print(sqrt)
print("Sum of all elements : ", ar2.sum())
print("Sum of elements column-wise : ", sum(ar2))
print("Highest element : ",ar2.max())
print("Lowest element : ", ar2.min())

[[2.82842712 1.73205081 3.        ]
 [1.         1.73205081 2.82842712]
 [1.41421356 1.73205081 1.        ]]
Sum of all elements :  38
Sum of elements column-wise :  [11  9 18]
Highest element :  9
Lowest element :  1


In [45]:
print(ar2)
# Now if I wanna find elements with specific conditions then :
print(np.where(ar2 == 8))
# It gives the element indexes which are equal to 8 in our array . Its type is tuple
print(np.where( ar2 > 7))    # Take first no. from output i.e. 0,0 which is 8 then 0,2 - 8 then 1,2 - 9
print(np.count_nonzero(ar2))  # counts no. of items that are not zero

[[8 3 9]
 [1 3 8]
 [2 3 1]]
(array([0, 1]), array([0, 2]))
(array([0, 0, 1]), array([0, 2, 2]))
9


In [46]:
import sys
# Numpy takes less storage then normal python program . See below to see how
python_arr = [2,44,67,33,6768]
numpy_arr = np.array(python_arr)

pysize = sys.getsizeof(1) * len(python_arr)
print("Size of normal python program : ", pysize)
npsize = numpy_arr.itemsize * numpy_arr.size
print("Size of numpy program : ",npsize)

Size of normal python program :  140
Size of numpy program :  40


In [47]:
# Numpy copy() function
# The copy() method creates a completely independent copy of the original array
# Modifying the copy will not affect the original array, and vice versa.
# It creates a new memory allocation for the copied data.
myarr = np.array([2,4,56,89,2])
copy_arr = myarr.copy()
myarr[2] = 99
print(myarr)
print(copy_arr)

print('\n')
# Numpy view() function
# The view() method creates a new array that is a "view" of the original array.
# Modifying the view will affect the original array, and vice versa.
# It does not create a new memory allocation for the data; instead, it provides a different "view" of the same data.
print(myarr)
view_arr = myarr.view()
myarr[4] = 80
print("myarr = ",myarr)
print("view_arr =",view_arr)

[ 2  4 99 89  2]
[ 2  4 56 89  2]


[ 2  4 99 89  2]
myarr =  [ 2  4 99 89 80]
view_arr = [ 2  4 99 89 80]


In [49]:
arrr1 = np.array([[3,4,5],[3,7,8]])
arrr2 = np.array([[3,4,5],[3,7,8]])
print(np.concatenate((arrr1,arrr2)))

[[3 4 5]
 [3 7 8]
 [3 4 5]
 [3 7 8]]
