<a href="https://colab.research.google.com/github/Suraj945gh/Antariksh/blob/main/Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
mydict = {
    'Name' : ['Rohan','Ram','Reet','Rahul'],
    'Dream' : ['IIT','NIT','IIMs','AIIMs'],
    'City' : ['Indore','Mumbai','Bangalore','Jhansi']
}
dframe = pd.DataFrame(mydict)
dframe
# Dataframe is simply an excelsheet that you can use in python

Name  Dream       City
0  Rohan    IIT     Indore
1    Ram    NIT     Mumbai
2   Reet   IIMs  Bangalore
3  Rahul  AIIMs     Jhansi

In [ ]:
dframe.to_csv('firstcsv.csv')
# This thing converts our data to csv file i.e. simply an excel file
# Go to the files section and you can view firstcsv file there

# Now if you don't want index in your dataframe then do this :
dframe.to_csv('firstcsv_no_index.csv',index=False)

In [ ]:
# If your dataframe is big then you can see first or last rows by :
dframe.head(2)   # Gives first 2 rows

Name Dream    City
0  Rohan   IIT  Indore
1    Ram   NIT  Mumbai

In [ ]:
dframe.tail(2)   # Gives last 2 rows

Name  Dream       City
2   Reet   IIMs  Bangalore
3  Rahul  AIIMs     Jhansi

In [ ]:
# Now if you wanna add a column that you'd forgotten just do this :
# Make a list first :
age = [17,18,22,25]
# Add it to the existing dataframe :
dframe['Age'] = age
dframe

Name  Dream       City  Age
0  Rohan    IIT     Indore   17
1    Ram    NIT     Mumbai   18
2   Reet   IIMs  Bangalore   22
3  Rahul  AIIMs     Jhansi   25

In [ ]:
dframe.describe()
# It gives an analysis of all the numerical data present in our df (dataframe)

Age
count   4.000000
mean   20.500000
std     3.696846
min    17.000000
25%    17.750000
50%    20.000000
75%    22.750000
max    25.000000

In [32]:
hello = pd.read_csv('Train_info.csv')
# This reads csv files from your computer

In [33]:
hello

Unnamed: 0  Train No.  Train Speed       City
0           0      23424           23     Indore
1           1      12332           25     Mumbai
2           2      23444           67  Bangalore
3           3      67445          123     Jhansi

In [31]:
hello['City']
# When it is a string the dtype becomes an object

0       Indore
1       Mumbai
2    Bangalore
3       Jhansi
Name: City, dtype: object

In [34]:
hello['Train Speed'][1] = 155
# Here we're changing the value of speed and it'll give a warning

<ipython-input-34-d07d7b218fe1>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hello['Train Speed'][1] = 155


In [35]:
hello

Unnamed: 0  Train No.  Train Speed       City
0           0      23424           23     Indore
1           1      12332          155     Mumbai
2           2      23444           67  Bangalore
3           3      67445          123     Jhansi

In [36]:
# Now , you can also change index content if you don't like starting from 0 :
hello.index = ['1st','2nd','3rd','4th']
hello

Unnamed: 0  Train No.  Train Speed       City
1st           0      23424           23     Indore
2nd           1      12332          155     Mumbai
3rd           2      23444           67  Bangalore
4th           3      67445          123     Jhansi

In [39]:
# How to delete unwanted columns from df :
del hello['Unnamed: 0']
hello

Train No.  Train Speed       City
1st      23424           23     Indore
2nd      12332          155     Mumbai
3rd      23444           67  Bangalore
4th      67445          123     Jhansi

In [40]:
# There are two datastructures in pandas : Series & Dataframe
# Series is an one-dimensional array (can be a row/column )
# Dataframe is a 2d array (is both rows & columns )

# Creating a random series with 10 elements
ser = pd.Series(np.random.rand(10))
ser

0    0.704012
1    0.539202
2    0.540127
3    0.051393
4    0.501363
5    0.742995
6    0.639586
7    0.482566
8    0.328616
9    0.473760
dtype: float64

In [41]:
type(ser)

pandas.core.series.Series

In [43]:
# Now making a large dataframe
# The numpy.random.rand() function creates an array of specified shape and fills it with random values
newdf = pd.DataFrame(np.random.rand(500,5))
newdf

0         1         2         3         4
0    0.568410  0.857567  0.534265  0.365483  0.722882
1    0.079831  0.703266  0.083403  0.388524  0.101558
2    0.776756  0.940241  0.219542  0.608692  0.180973
3    0.531729  0.495145  0.394695  0.796670  0.468861
4    0.910313  0.530947  0.820365  0.576964  0.009827
..        ...       ...       ...       ...       ...
495  0.282543  0.775591  0.045051  0.120704  0.571281
496  0.077019  0.829738  0.223568  0.295695  0.641760
497  0.743361  0.082366  0.650392  0.638952  0.488005
498  0.922614  0.655045  0.906703  0.377726  0.176067
499  0.120058  0.783895  0.611686  0.160528  0.770527

[500 rows x 5 columns]

In [44]:
type(newdf)   # Its type is a dataframe

pandas.core.frame.DataFrame

In [46]:
newdf.describe()

0           1           2           3           4
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean     0.511864    0.527020    0.492917    0.524763    0.490746
std      0.282891    0.290242    0.291154    0.287214    0.283636
min      0.000955    0.009257    0.003394    0.001430    0.000979
25%      0.271478    0.269122    0.223251    0.295562    0.242966
50%      0.523669    0.550484    0.495174    0.530701    0.487308
75%      0.752978    0.774495    0.755048    0.775149    0.721747
max      0.998666    0.999204    0.999621    0.992825    0.997092

In [49]:
print(newdf.dtypes)
newdf.head()

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object


0         1         2         3         4
0  0.568410  0.857567  0.534265  0.365483  0.722882
1  0.079831  0.703266  0.083403  0.388524  0.101558
2  0.776756  0.940241  0.219542  0.608692  0.180973
3  0.531729  0.495145  0.394695  0.796670  0.468861
4  0.910313  0.530947  0.820365  0.576964  0.009827

In [52]:
print(newdf.index)
print(newdf.columns)

RangeIndex(start=0, stop=5, step=1)


In [57]:
# Converting this thing to numpy array
nparr = newdf.to_numpy()
print(nparr)
print(nparr.dtype)

[[0.56841035 0.85756679 0.5342645  0.36548318 0.72288239]
 [0.07983065 0.7032656  0.08340337 0.3885241  0.10155783]
 [0.77675636 0.9402409  0.21954173 0.60869242 0.18097292]
 ...
 [0.7433614  0.08236582 0.65039175 0.63895175 0.48800539]
 [0.92261396 0.65504464 0.90670284 0.37772608 0.17606722]
 [0.12005762 0.78389479 0.61168595 0.16052789 0.77052675]]
float64


In [59]:
newdf.T
# This has converted our rows into columns and vice-versa i.e. Transpose

0         1         2         3         4         5         6    \
0  0.568410  0.079831  0.776756  0.531729  0.910313  0.143383  0.213538   
1  0.857567  0.703266  0.940241  0.495145  0.530947  0.200342  0.878394   
2  0.534265  0.083403  0.219542  0.394695  0.820365  0.141960  0.587259   
3  0.365483  0.388524  0.608692  0.796670  0.576964  0.643452  0.594607   
4  0.722882  0.101558  0.180973  0.468861  0.009827  0.869261  0.947001   

        7         8         9    ...       490       491       492       493  \
0  0.068020  0.306810  0.275034  ...  0.134362  0.670066  0.893804  0.490890   
1  0.017121  0.417934  0.409533  ...  0.587054  0.737282  0.109251  0.886005   
2  0.750113  0.845479  0.426148  ...  0.957710  0.252740  0.946648  0.154691   
3  0.501102  0.046569  0.810310  ...  0.102968  0.653137  0.203793  0.229452   
4  0.335798  0.298222  0.627117  ...  0.851408  0.004025  0.641019  0.650252   

        494       495       496       497       498       499  
0  0.628632  0.282543  0.077019  0.743361  0.922614  0.120058  
1  0.878754  0.775591  0.829738  0.082366  0.655045  0.783895  
2  0.117322  0.045051  0.223568  0.650392  0.906703  0.611686  
3  0.337850  0.120704  0.295695  0.638952  0.377726  0.160528  
4  0.988333  0.571281  0.641760  0.488005  0.176067  0.770527  

[5 rows x 500 columns]

In [62]:
newdf.sort_index(axis=0 ,ascending=False)
# Sorting the df from reverse order

0         1         2         3         4
499  0.120058  0.783895  0.611686  0.160528  0.770527
498  0.922614  0.655045  0.906703  0.377726  0.176067
497  0.743361  0.082366  0.650392  0.638952  0.488005
496  0.077019  0.829738  0.223568  0.295695  0.641760
495  0.282543  0.775591  0.045051  0.120704  0.571281
..        ...       ...       ...       ...       ...
4    0.910313  0.530947  0.820365  0.576964  0.009827
3    0.531729  0.495145  0.394695  0.796670  0.468861
2    0.776756  0.940241  0.219542  0.608692  0.180973
1    0.079831  0.703266  0.083403  0.388524  0.101558
0    0.568410  0.857567  0.534265  0.365483  0.722882

[500 rows x 5 columns]

In [65]:
print(type(newdf[0]))
newdf[0]

<class 'pandas.core.series.Series'>


0      0.568410
1      0.079831
2      0.776756
3      0.531729
4      0.910313
         ...   
495    0.282543
496    0.077019
497    0.743361
498    0.922614
499    0.120058
Name: 0, Length: 500, dtype: float64

In [68]:
newdf2 = newdf
# Here newdf2 is a view of newdf i.e. when values of newdf2 changes newdf also changes
# This is because newdf2 is pointing to newdf
newdf2[0][0] = 555

In [72]:
newdf.head()
# here the first element has changed to 555

0         1         2         3         4
0  555.000000  0.857567  0.534265  0.365483  0.722882
1    0.079831  0.703266  0.083403  0.388524  0.101558
2    0.776756  0.940241  0.219542  0.608692  0.180973
3    0.531729  0.495145  0.394695  0.796670  0.468861
4    0.910313  0.530947  0.820365  0.576964  0.009827

In [71]:
newdf3 = newdf.copy()
# We made newdf3 a copy of newdf
# This means that if you change values of newdf3 , this won't change content in newdf
newdf3[0][0] = 99
print(newdf)      # 1st element doesn't change

              0         1         2         3         4
0    555.000000  0.857567  0.534265  0.365483  0.722882
1      0.079831  0.703266  0.083403  0.388524  0.101558
2      0.776756  0.940241  0.219542  0.608692  0.180973
3      0.531729  0.495145  0.394695  0.796670  0.468861
4      0.910313  0.530947  0.820365  0.576964  0.009827
..          ...       ...       ...       ...       ...
495    0.282543  0.775591  0.045051  0.120704  0.571281
496    0.077019  0.829738  0.223568  0.295695  0.641760
497    0.743361  0.082366  0.650392  0.638952  0.488005
498    0.922614  0.655045  0.906703  0.377726  0.176067
499    0.120058  0.783895  0.611686  0.160528  0.770527

[500 rows x 5 columns]


In [74]:
newdf.columns = list('ABCDE')
# You can change values with loc function
newdf.loc[0][0] = 234
newdf.head(2)

A         B         C         D         E
0  234.000000  0.857567  0.534265  0.365483  0.722882
1    0.079831  0.703266  0.083403  0.388524  0.101558

In [87]:
# loc method
# You can locate rows by their index number.
print(newdf.loc[1])

# You can also locate multiple rows at once by providing a list of index numbers
print(newdf.loc[[2,5,8]])

# You can locate specific cells by specifying both the row and column
print('Required element = ',newdf.loc[1]['A'])

A         0.079831
B         0.703266
C         0.083403
D         0.388524
E         0.101558
cancel         NaN
Name: 1, dtype: float64
          A         B         C         D         E  cancel
2  0.776756  0.940241  0.219542  0.608692  0.180973     NaN
5  0.143383  0.200342  0.141960  0.643452  0.869261     NaN
8  0.306810  0.417934  0.845479  0.046569  0.298222     NaN
Required element =  0.07983065436597703


In [94]:
newdf.loc[0,'cancel'] = 37
print(newdf.head())

# Since , I created cancel column unnecessarily , I can delete it by drop method :
# drop method will return a new df and doesn't change the original one , since it returns a copy
# so save it in newdf only
newdf = newdf.drop('cancel',axis=1)   # Here by default , axis is
newdf

            A         B         C         D         E  cancel
0  234.000000  0.857567  0.534265  0.365483  0.722882    37.0
1    0.079831  0.703266  0.083403  0.388524  0.101558     NaN
2    0.776756  0.940241  0.219542  0.608692  0.180973     NaN
3    0.531729  0.495145  0.394695  0.796670  0.468861     NaN
4    0.910313  0.530947  0.820365  0.576964  0.009827     NaN


A         B         C         D         E
0    234.000000  0.857567  0.534265  0.365483  0.722882
1      0.079831  0.703266  0.083403  0.388524  0.101558
2      0.776756  0.940241  0.219542  0.608692  0.180973
3      0.531729  0.495145  0.394695  0.796670  0.468861
4      0.910313  0.530947  0.820365  0.576964  0.009827
..          ...       ...       ...       ...       ...
495    0.282543  0.775591  0.045051  0.120704  0.571281
496    0.077019  0.829738  0.223568  0.295695  0.641760
497    0.743361  0.082366  0.650392  0.638952  0.488005
498    0.922614  0.655045  0.906703  0.377726  0.176067
499    0.120058  0.783895  0.611686  0.160528  0.770527

[500 rows x 5 columns]

In [95]:
newdf.loc[[2,4],:]
# Here : means all the rows

A         B         C         D         E
2  0.776756  0.940241  0.219542  0.608692  0.180973
4  0.910313  0.530947  0.820365  0.576964  0.009827

In [107]:
# You can also add conditions in loc like
newdf.loc[(newdf['B'] < 0.02) & (newdf['C'] > 0.01)]

A         B         C         D         E
7    0.068020  0.017121  0.750113  0.501102  0.335798
54   0.803771  0.009257  0.373529  0.961061  0.691971
91   0.510150  0.013882  0.210047  0.729330  0.476032
151  0.082175  0.013961  0.864063  0.383498  0.720647
192  0.819821  0.015647  0.440832  0.101784  0.321536
220  0.582352  0.013001  0.395899  0.461667  0.679071
222  0.051772  0.016473  0.209727  0.616035  0.781614
371  0.780153  0.017594  0.102120  0.777770  0.546655
445  0.484411  0.010427  0.034117  0.527086  0.112080
463  0.422521  0.015241  0.982528  0.562061  0.870694

In [109]:
# If you wanna access elements by indexing only then use iloc method
# Remember that loc() is for accessing through row/col names and not index
newdf.iloc[222][2]

0.20972703310798124

In [113]:
newdf.iloc[[151,0], [0,1]]
#          [rows],[columns]

A         B
151    0.082175  0.013961
0    234.000000  0.857567

In [ ]:
newdf.head()
newdf.drop(['A','E'], axis=1 inplace=True)
# We know that the above one is a copy , but inplace attribute deletes from the original dataframe
# Also remember that , running it more than once could cause an error

In [123]:
newdf.drop([1,3,4],inplace = True , axis = 0)

In [125]:
newdf.head(5)

B         C         D
0  0.857567  0.534265  0.365483
2  0.940241  0.219542  0.608692
5  0.200342  0.141960  0.643452
6  0.878394  0.587259  0.594607
7  0.017121  0.750113  0.501102

In [129]:
# Resetting index since we deleted rows 1,3,4
# Remember that content is deleted permanently , only reserialing is done
newdf.reset_index(drop=True , inplace = True)
# Here drop ensures that another index col doesn't come
newdf

B         C         D
0    0.857567  0.534265  0.365483
1    0.940241  0.219542  0.608692
2    0.200342  0.141960  0.643452
3    0.878394  0.587259  0.594607
4    0.017121  0.750113  0.501102
..        ...       ...       ...
492  0.775591  0.045051  0.120704
493  0.829738  0.223568  0.295695
494  0.082366  0.650392  0.638952
495  0.655045  0.906703  0.377726
496  0.783895  0.611686  0.160528

[497 rows x 3 columns]

In [137]:
# Always use loc or iloc for setting values
newdf.loc[: ,['B']] = None
newdf

B         C         D
0    None  0.534265  0.365483
1    None  0.219542  0.608692
2    None  0.141960  0.643452
3    None  0.587259  0.594607
4    None  0.750113  0.501102
..    ...       ...       ...
492  None  0.045051  0.120704
493  None  0.223568  0.295695
494  None  0.650392  0.638952
495  None  0.906703  0.377726
496  None  0.611686  0.160528

[497 rows x 3 columns]

In [139]:
newdf.shape

(497, 3)

In [140]:
newdf.info()  # Gives all info abt particular dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   B       0 non-null      object 
 1   C       497 non-null    float64
 2   D       497 non-null    float64
dtypes: float64(2), object(1)
memory usage: 11.8+ KB


In [133]:
# dropna() method
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})
df

name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [134]:
# Now , I don't want NaN elements , so :
df = df.dropna()
df
# also attribute like (how='all',axis =1 ) will remove nan only if all the elements of the row contains it

name        toy       born
1  Batman  Batmobile 1940-04-25

In [145]:
df.isnull()

name    toy   born
1  False  False  False

In [144]:
df.notnull()

name   toy  born
1  True  True  True

In [142]:
newdf.notnull()

B     C     D
0    False  True  True
1    False  True  True
2    False  True  True
3    False  True  True
4    False  True  True
..     ...   ...   ...
492  False  True  True
493  False  True  True
494  False  True  True
495  False  True  True
496  False  True  True

[497 rows x 3 columns]

In [149]:
# Task : to create dataframe of ints of 3 rows and 2 columns and run methods on them
dict1 = {
    1 : [56, 77 , 345] , 2 : [23 , 567 , 345]
}
mydf = pd.DataFrame(dict1)
mydf

1    2
0   56   23
1   77  567
2  345  345

In [150]:
mydf.describe()

1           2
count    3.000000    3.000000
mean   159.333333  311.666667
std    161.134519  273.527573
min     56.000000   23.000000
25%     66.500000  184.000000
50%     77.000000  345.000000
75%    211.000000  456.000000
max    345.000000  567.000000

In [151]:
mydf.mean()

1    159.333333
2    311.666667
dtype: float64

In [152]:
mydf.corr()
# The corr() aggregate function returns a coefficient of correlation between two numbers.

1         2
1  1.000000  0.170113
2  0.170113  1.000000

In [154]:
mydf.median()

1     77.0
2    345.0
dtype: float64

In [155]:
mydf.mode()

1    2
0   56   23
1   77  345
2  345  567